-- Bundled comparison fixture for the asb-detection-compare GitHub Action.
--
-- Auto-generated by scripts/build-fixture.php from a real corpus, stratified
-- by antispam_bee_reason + comment_type (<=10 rows each). PII removed: author,
-- e-mail and IP are synthetic for every row, comment IDs are renumbered from 1
-- (original IDs discarded), and ham content is synthetic; spam content/URLs are
-- kept because the rules act on them. Do not edit by hand.
-- Rows: 122.
--
-- Groups (source antispam_bee_reason; up to 10 rows each):
--   (ham)           24  comment ×10, pingback ×10, trackback ×4 legitimate comments (content synthesized; envelope anonymized)
--   css             10  comment ×10           honeypot / CSS decoy catch (content replayed via the visible field)
--   empty           10  comment ×10           empty comment body
--   localdb         28  comment ×10, pingback ×9, trackback ×9 local-DB spam (IP / e-mail / URL seen before)
--   manually        30  comment ×10, pingback ×10, trackback ×10 manually marked as spam
--   regexp          10  comment ×10           matched a spam regex pattern
--   title_is_name   10  trackback ×10         linkback title equals the blog name

DROP TABLE IF EXISTS wp_comments;
CREATE TABLE wp_comments (
	comment_ID           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	comment_content      TEXT,
	comment_author       TINYTEXT,
	comment_author_email VARCHAR(100) DEFAULT '',
	comment_author_url   VARCHAR(200) DEFAULT '',
	comment_author_IP    VARCHAR(100) DEFAULT '',
	comment_agent        VARCHAR(255) DEFAULT '',
	comment_type         VARCHAR(20)  DEFAULT 'comment',
	PRIMARY KEY (comment_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS wp_commentmeta;
CREATE TABLE wp_commentmeta (
	meta_id    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	comment_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
	meta_key   VARCHAR(255) DEFAULT NULL,
	meta_value LONGTEXT,
	PRIMARY KEY (meta_id),
	KEY comment_id (comment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- (ham) — 24 row(s) [comment ×10, pingback ×10, trackback ×4] — legitimate comments (content synthesized; envelope anonymized)
INSERT INTO wp_comments
	(comment_ID, comment_content, comment_author, comment_author_email, comment_author_url, comment_author_IP, comment_agent, comment_type)
VALUES
	(1, 'Thanks, this walkthrough finally made the setup click for me.', 'Commenter 1', 'user1@example.com', '', '198.51.100.2', '', 'comment'),
	(2, 'Does this also work on a multisite install? Great write-up either way.', 'Commenter 2', 'user2@example.com', '', '203.0.113.3', '', 'comment'),
	(3, 'I hit the same issue last week; clearing the object cache fixed it.', 'Commenter 3', 'user3@example.com', '', '198.51.100.4', '', 'comment'),
	(4, 'Bookmarked — looking forward to the follow-up on caching.', 'Commenter 4', 'user4@example.com', '', '203.0.113.5', '', 'comment'),
	(5, 'Small typo in step three, but otherwise perfect. Cheers!', 'Commenter 5', 'user5@example.com', '', '198.51.100.6', '', 'comment'),
	(6, 'We rolled this out to staging today and it just works. Thank you.', 'Commenter 6', 'user6@example.com', '', '203.0.113.7', '', 'comment'),
	(7, 'Could you add a short section on backups? Otherwise very clear.', 'Commenter 7', 'user7@example.com', '', '198.51.100.8', '', 'comment'),
	(8, 'The diagram really helped me understand the flow.', 'Commenter 8', 'user8@example.com', '', '203.0.113.9', '', 'comment'),
	(9, 'Exactly what I needed, thanks for taking the time to write it up.', 'Commenter 9', 'user9@example.com', '', '198.51.100.10', '', 'comment'),
	(10, 'Works on PHP 8.3 for me as well, no changes required.', 'Commenter 10', 'user10@example.com', '', '203.0.113.11', '', 'comment'),
	(11, 'Thanks, this walkthrough finally made the setup click for me.', 'Commenter 11', 'user11@example.com', '', '198.51.100.12', '', 'pingback'),
	(12, 'Does this also work on a multisite install? Great write-up either way.', 'Commenter 12', 'user12@example.com', '', '203.0.113.13', '', 'pingback'),
	(13, 'I hit the same issue last week; clearing the object cache fixed it.', 'Commenter 13', 'user13@example.com', '', '198.51.100.14', '', 'pingback'),
	(14, 'Bookmarked — looking forward to the follow-up on caching.', 'Commenter 14', 'user14@example.com', '', '203.0.113.15', '', 'pingback'),
	(15, 'Small typo in step three, but otherwise perfect. Cheers!', 'Commenter 15', 'user15@example.com', '', '198.51.100.16', '', 'pingback'),
	(16, 'We rolled this out to staging today and it just works. Thank you.', 'Commenter 16', 'user16@example.com', '', '203.0.113.17', '', 'pingback'),
	(17, 'Could you add a short section on backups? Otherwise very clear.', 'Commenter 17', 'user17@example.com', '', '198.51.100.18', '', 'pingback'),
	(18, 'The diagram really helped me understand the flow.', 'Commenter 18', 'user18@example.com', '', '203.0.113.19', '', 'pingback'),
	(19, 'Exactly what I needed, thanks for taking the time to write it up.', 'Commenter 19', 'user19@example.com', '', '198.51.100.20', '', 'pingback'),
	(20, 'Works on PHP 8.3 for me as well, no changes required.', 'Commenter 20', 'user20@example.com', '', '203.0.113.21', '', 'pingback'),
	(21, 'Thanks, this walkthrough finally made the setup click for me.', 'Commenter 21', 'user21@example.com', '', '198.51.100.22', 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0', 'trackback'),
	(22, 'Does this also work on a multisite install? Great write-up either way.', 'Commenter 22', 'user22@example.com', '', '203.0.113.23', 'Opera/9.80 (J2ME/MIDP; Opera Mini/4.2.21992/22.387; U; vi) Presto/2.5.25 Version/10.54', 'trackback'),
	(23, 'I hit the same issue last week; clearing the object cache fixed it.', 'Commenter 23', 'user23@example.com', '', '198.51.100.24', 'Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.2.13) Gecko/20101206 Ubuntu/10.10 (maverick) Firefox/3.6.13', 'trackback'),
	(24, 'Bookmarked — looking forward to the follow-up on caching.', 'Commenter 24', 'user24@example.com', '', '203.0.113.25', 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4pre) Gecko/2008021204 Minefield/3.0b4pre', 'trackback');

-- css — 10 row(s) [comment ×10] — honeypot / CSS decoy catch (content replayed via the visible field)
INSERT INTO wp_comments
	(comment_ID, comment_content, comment_author, comment_author_email, comment_author_url, comment_author_IP, comment_agent, comment_type)
VALUES
	(25, '<a href="https://sortedfood.hubase.info/mIOt2HCJk4-Bo2U/sushi-recipe" rel="nofollow ugc"></a>
 
SUSHI Recipe Relay <a href="https://sortedfood.hubase.info/mIOt2HCJk4-Bo2U/sushi-recipe" rel="nofollow ugc">ChallengePass</a> It On S2 E11', 'Commenter 25', 'user25@example.com', 'https://sortedfood.hubase.info/mIOt2HCJk4-Bo2U/sushi-recipe', '198.51.100.26', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.44 Safari/537.36', 'comment'),
	(26, 'Looking forward for income? Get it online. 
Link - https://24crypto.de/btc-cryptocurrency-market.php', 'Commenter 26', 'user26@example.com', 'https://24crypto.de/bitcoin-trading-africa.php', '203.0.113.27', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4100.3 Safari/537.36', 'comment'),
	(27, 'Has anyone ever shopped at Mega Vape Digital Smoke Boutique? :)', 'Commenter 27', 'user27@example.com', 'https://addictedtospurs.co.uk/vapor-connoisseur-hemp-and-cbd-store-near-stidham-74461-ok-129794', '198.51.100.28', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(28, 'Has anyone ever been to Vapor Emporium? :-)', 'Commenter 28', 'user28@example.com', 'https://addictedtospurs.co.uk/designated-vaping-vape-store-situated-in-midvale-84047-ut-135831', '203.0.113.29', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(29, 'mns5562utr lS3XGI5 zLLw A1oQur0', 'Commenter 29', 'user29@example.com', '', '198.51.100.30', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.44 Safari/537.36', 'comment'),
	(30, 'Thousands of bucks are guaranteed if you use this robot. 
Link - - https://24crypto.de/futures-trading-bitcoin-reddit.php', 'Commenter 30', 'user30@example.com', 'https://24crypto.de/btc-profit-italy-recensioni.php', '203.0.113.31', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4098.0 Safari/537.36', 'comment'),
	(31, 'Trust the financial Bot to become rich. 
Link - https://24crypto.de/how-to-bitcoin-trade.php', 'Commenter 31', 'user31@example.com', 'https://24crypto.de/bitcoin-money-market.php', '198.51.100.32', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.37', 'comment'),
	(32, '# 1 financial expert in the net! Check out the new Robot. 
Link - https://24crypto.de/bitcoin-trader-late-night-berlin.php', 'Commenter 32', 'user32@example.com', 'https://24crypto.de/marketexile-bitcoin-generator.php', '203.0.113.33', 'Mozilla/5.0 (Windows NT 10.0; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.34 Safari/537.36 Edg/83.0.478.25', 'comment'),
	(33, '<a href="https://shortcircuit.alnets.info/qLmur7nTwJd21Jw/did-hp" rel="nofollow ugc"></a>
 
Did HP make a Dell <a href="https://shortcircuit.alnets.info/qLmur7nTwJd21Jw/did-hp" rel="nofollow ugc">XPS</a> 15 killer???', 'Commenter 33', 'user33@example.com', 'https://shortcircuit.alnets.info/qLmur7nTwJd21Jw/did-hp', '198.51.100.34', 'Mozilla/5.0 (Windows NT 10.0; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36', 'comment'),
	(34, 'Online job can be really effective if you use this Robot. 
Link - https://24crypto.de/como-ser-trader-no-mercado-bitcoin.php', 'Commenter 34', 'user34@example.com', 'https://24crypto.de/how-to-make-money-from-bitcoin-trading.php', '203.0.113.35', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4096.0 Safari/537.36', 'comment');

-- empty — 10 row(s) [comment ×10] — empty comment body
INSERT INTO wp_comments
	(comment_ID, comment_content, comment_author, comment_author_email, comment_author_url, comment_author_IP, comment_agent, comment_type)
VALUES
	(35, '', 'Commenter 35', 'user35@example.com', 'https://emailtrackerapi.leadforensics.com/api/URLOpen?EmailSentRecordID=17006&amp;URL=https://www.juicylinks.io', '198.51.100.36', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(36, '', 'Commenter 36', 'user36@example.com', 'http://www.fudou-san.com/link/rank.cgi?mode=link&amp;url=http://www.postfallsphotographer.com', '203.0.113.37', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(37, '', 'Commenter 37', 'user37@example.com', 'https://www.kyrktorget.se/includes/statsaver.php?type=ext&amp;id=2067&amp;url=backboneleaders.com/', '198.51.100.38', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(38, '', 'Commenter 38', 'user38@example.com', 'http://tourismchiangrai.com/goto.php?id=6&amp;goto=https://www.postfallsbootcamp.com', '203.0.113.39', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(39, '', 'Commenter 39', 'user39@example.com', 'http://pram.elmercurio.com/Logout.aspx?ApplicationName=SOYCHILE&amp;l=yes&amp;SSOTargeturl=spokanevalleywebdesign.com', '198.51.100.40', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(40, '', 'Commenter 40', 'user40@example.com', 'http://e.ourger.com/?c=scene&amp;a=link&amp;id=47154371&amp;url=https://www.marketingpostfalls.com', '203.0.113.41', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(41, '', 'Commenter 41', 'user41@example.com', 'https://www.24livenewspaper.com/third/?url=www.hiddenapples.com/', '198.51.100.42', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(42, '', 'Commenter 42', 'user42@example.com', 'https://www.yamanashi-kosodate.net/blog/count?id=34&amp;url=http://www.hiddenapples.com', '203.0.113.43', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(43, '', 'Commenter 43', 'user43@example.com', 'http://www.bikc.ru/gourl.php?go=www.spokanevalleymarketing.com', '198.51.100.44', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment'),
	(44, '', 'Commenter 44', 'user44@example.com', 'http://www.prokhorovfund.ru/bitrix/rk.php?id=14&amp;event1=banner&amp;event2=click&amp;event3=1+2F+5B145D+5Bsecond_page_2005D+XI+CAD0DFCACA&amp;goto=https://ocrvcenter.com/', '203.0.113.45', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'comment');

-- localdb — 28 row(s) [comment ×10, pingback ×9, trackback ×9] — local-DB spam (IP / e-mail / URL seen before)
INSERT INTO wp_comments
	(comment_ID, comment_content, comment_author, comment_author_email, comment_author_url, comment_author_IP, comment_agent, comment_type)
VALUES
	(45, 'Greetz', 'Commenter 45', 'user45@example.com', '', '198.51.100.46', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36', 'comment'),
	(46, 'Karen cole paper LLC', 'Commenter 46', 'user46@example.com', '', '203.0.113.47', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36', 'comment'),
	(47, 'Rotometrics', 'Commenter 47', 'user47@example.com', '', '198.51.100.48', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 Edg/90.0.818.42', 'comment'),
	(48, 'TamTam Design Studio', 'Commenter 48', 'user48@example.com', '', '203.0.113.49', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'comment'),
	(49, 'https://www.gladwingroup.com/interactive-led-flat-panel-display-supreme-9-series.php

Adopt full aluminium alloy panel structure, anodized surface process, ultra-narrow frame, rounded corner design, fashion and beautiful appearance
4mm tempered glass with anti glare 3.Advanced IR 20 touching technology.
The OPS host module adopts plug structure design, internal Inter standard 80pin interface, without any external power line and signal line, which is convenient for inspection, maintenance and upgrade, and achieves the aesthetic effect of the machine
Front side interface: Public USB*3,Touch-USB*1,HDMI*1
Front 8 buttons: POWER ,Input ,Menu, V+, V-, ECO, Home, PC-POWER(Power button for OPS PC only)
Front side speakers, Prevents noise distortion due to embedding

<a href="https://www.gladwingroup.com/interactive-led-flat-panel-display-supreme-9-series" rel="nofollow ugc">INTERACTIVE LED FALT PANEL</a>', 'Commenter 49', 'user49@example.com', 'https://www.gladwingroup.com/interactive-led-flat-panel-display-supreme-9-series.php', '198.51.100.50', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36', 'comment'),
	(50, 'https://www.gladwingroup.com/interactive-led-flat-panel-display-supreme-9-series.php

Adopt full aluminium alloy panel structure, anodized surface process, ultra-narrow frame, rounded corner design, fashion and beautiful appearance
4mm tempered glass with anti glare 3.Advanced IR 20 touching technology.
The OPS host module adopts plug structure design, internal Inter standard 80pin interface, without any external power line and signal line, which is convenient for inspection, maintenance and upgrade, and achieves the aesthetic effect of the machine
Front side interface: Public USB*3,Touch-USB*1,HDMI*1
Front 8 buttons: POWER ,Input ,Menu, V+, V-, ECO, Home, PC-POWER(Power button for OPS PC only)
Front side speakers, Prevents noise distortion due to embedding

<a href="https://www.gladwingroup.com/interactive-led-flat-panel-display-supreme-9-series" rel="nofollow ugc">INTERACTIVE LED FALT PANEL</a>', 'Commenter 50', 'user50@example.com', 'https://www.gladwingroup.com/interactive-led-flat-panel-display-supreme-9-series.php', '203.0.113.51', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36', 'comment'),
	(51, 'Hello Bern,
  
"Wow, I never knew that marking an affiliate link with the word "sponsored" wasn\'t enough to satisfy the judge in Germany. Thanks for sharing this information and your thoughts on it. I think using "affiliate link" might be the best option for clarity."

"As a tech enthusiast, I was looking up the full form of USB and stumbled upon this insightful comment about affiliate marketing regulations in Germany. It\'s interesting to see the legal complexities involved in this field. Thanks for sharing your experience!"

"I recently got my hands on the OnePlus 9 and was curious about the full form of USB when I came across this comment. It\'s amazing how one can find relevant information on any topic on YouTube. Thanks for sharing your insights on affiliate marketing regulations in Germany, it\'s definitely an important aspect to consider."', 'Commenter 51', 'user51@example.com', 'https://www.spark9026.online', '198.51.100.52', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36/8mqEzXuL-46', 'comment'),
	(52, 'Step 1
git config --global user.signkey ~/.ssh/id_ed25519

should be

git config --global user.signingKey ~/.ssh/id_ed25519

Tested with git version 2.41.0', 'Commenter 52', 'user52@example.com', '', '203.0.113.53', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36', 'comment'),
	(53, 'Very useful tutorial, thanks!', 'Commenter 53', 'user53@example.com', 'https://www.voan.ch', '198.51.100.54', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0', 'comment'),
	(54, 'How can I sort on an ACF field stored in a Custom Post Type.
I tried to change "p.post_title" with "postmeta.last_name" but it does not work.
Where should I put the order asc?
Thanks in advance.', 'Commenter 54', 'user54@example.com', '', '203.0.113.55', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36', 'comment'),
	(55, '[&#8230;]  Read Full Article  [&#8230;]', 'Commenter 55', 'user55@example.com', 'https://www.wpnews.io/how-to-get-rid-of-the-2-suffix-on-a-page/', '198.51.100.56', 'The Incutio XML-RPC PHP Library -- WordPress/6.4.1', 'pingback'),
	(56, '[&#8230;] Fontehttps://kau-boys.com/3052/web-development/repair-a-broken-git-repository-file-system [&#8230;]', 'Commenter 56', 'user56@example.com', 'https://devopsmind.com.br/troubleshooting/git-erro-corrupt-fatal-loose-object-stored-in-git-objects-is-corrupt/', '203.0.113.57', 'The Incutio XML-RPC PHP Library -- WordPress/6.2.4', 'pingback'),
	(57, '[&#8230;] his article &#8220;Adding some Colors to the Block Theme&#8220;, Bernhard Kau discusses how to best add various color options to a block theme. It&#8217;s a [&#8230;]', 'Commenter 57', 'user57@example.com', 'https://gutenbergtimes.com/grid-layouts-are-coming-playground-for-preview-interactivity-api-in-the-wild-weekend-edition-291/', '198.51.100.58', 'The Incutio XML-RPC PHP Library -- WordPress/6.5.2', 'pingback'),
	(58, '[&#8230;] his tutorial Bringing some structure into the theme: The Sidebar, Bernhard Kau walks you through the steps, he used to add a sidebar to his theme all in the site [&#8230;]', 'Commenter 58', 'user58@example.com', 'https://gutenbergtimes.com/wordpress-6-6-roadmap-demos-whats-next-for-meta-boxes-pattern-tutorials-weekend-edition-293/', '203.0.113.59', 'The Incutio XML-RPC PHP Library -- WordPress/6.5.2', 'pingback'),
	(59, '[&#8230;] own Bernhard Kau shared his perspective on the event, and emphasized the importance of this approach, highlighting how genuine connections [&#8230;]', 'Commenter 59', 'user59@example.com', 'https://syde.com/wordcamp-leipzig-2023/', '198.51.100.60', 'The Incutio XML-RPC PHP Library -- WordPress/6.5.2', 'pingback'),
	(60, '[&#8230;] his post Moving the sidebar into a theme pattern  Bernhard Kau continues to share in on his block theme building [&#8230;]', 'Commenter 60', 'user60@example.com', 'https://gutenbergtimes.com/wordpress-6-6-beta-1-blueprints-to-powered-playground-block-bindings-api-tutorial-and-so-much-more-weekend-edition-295/', '203.0.113.61', 'The Incutio XML-RPC PHP Library -- WordPress/6.5.4', 'pingback'),
	(61, '[&#8230;] Kau continued his series on building block theme for his website with Goal missed: I had to add some CSS to the theme. Although determined to only use the Site editor to create his theme, the difficulties to designing [&#8230;]', 'Commenter 61', 'user61@example.com', 'https://gutenbergtimes.com/learn-wordpress-redesign-woocommerce-the-future-is-block-based-starter-themes-and-a-lot-more-weekend-edition-301/', '198.51.100.62', 'The Incutio XML-RPC PHP Library -- WordPress/6.6.1', 'pingback'),
	(62, '[&#8230;]  Read Full Article  [&#8230;]', 'Commenter 62', 'user62@example.com', 'https://www.wpnews.io/implementing-a-custom-block-style-variation-using-only-json-files/', '203.0.113.63', 'The Incutio XML-RPC PHP Library -- WordPress/6.8.1', 'pingback'),
	(63, '[&#8230;]  Read Full Article  [&#8230;]', 'Commenter 63', 'user63@example.com', 'https://www.wpnews.io/fixing-slow-woocommerce-logins-15-million-order-notes-and-two-comments/', '198.51.100.64', 'The Incutio XML-RPC PHP Library -- WordPress/6.8.2', 'pingback'),
	(64, '<strong>1packard</strong>

', 'Commenter 64', 'user64@example.com', 'https://kau-boys.com', '203.0.113.65', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36', 'trackback'),
	(65, '<strong>2apoplectic</strong>

', 'Commenter 65', 'user65@example.com', 'https://kau-boys.com', '198.51.100.66', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36', 'trackback'),
	(66, '<strong>3emotionally</strong>

', 'Commenter 66', 'user66@example.com', 'https://kau-boys.com', '203.0.113.67', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'trackback'),
	(67, '<strong>1inspector</strong>

', 'Commenter 67', 'user67@example.com', 'https://kau-boys.com', '198.51.100.68', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'trackback'),
	(68, '<strong>canadian pharmacies without an rx https://otoplenie-castnogo-doma.webnode.com.ua/l/kotel-dlya-otopleniya-chastnogo-doma/</strong>

Regards. Loads of tips!', 'Commenter 68', 'user68@example.com', 'https://otoplenie-castnogo-doma.webnode.com.ua/l/kotel-dlya-otopleniya-chastnogo-doma/', '203.0.113.69', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3082.15 Safari/537.36', 'trackback'),
	(69, '<strong>Cheap cialis http://andere.strikingly.com/</strong>

Amazing a lot of awesome info!', 'Commenter 69', 'user69@example.com', 'http://andere.strikingly.com/', '198.51.100.70', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3096.61 Safari/537.36', 'trackback'),
	(70, '<strong>cialis 5mg https://canadianpharmaceuticalsonline.home.blog/</strong>

Amazing loads of good information.', 'Commenter 70', 'user70@example.com', 'https://canadianpharmaceuticalsonline.home.blog/', '203.0.113.71', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2873.10 Safari/537.36', 'trackback'),
	(71, '<strong>... [Trackback]</strong>

[...] There you will find 82332 more Infos: kau-boys.com/2578/wordpress/translate-a-plugin-or-theme-without-additional-software-or-plugins [...]', 'Commenter 71', 'user71@example.com', 'http://www.T0nkp4Fj.net', '198.51.100.72', 'Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.2.16) Gecko/20110323 Ubuntu/10.04 (lucid) Firefox/3.6.16', 'trackback'),
	(72, '<strong>... [Trackback]</strong>

[...] Read More here: kau-boys.com/2358/web-development/a-few-easy-steps-to-make-a-navigation-more-accessible/trackback/ [...]', 'Commenter 72', 'user72@example.com', 'http://www.h6XT9.com', '203.0.113.73', 'Mozilla/4.0 (compatible; MSIE 6.0; AOL 9.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; Seekmo 10.0.406.0)', 'trackback');

-- manually — 30 row(s) [comment ×10, pingback ×10, trackback ×10] — manually marked as spam
INSERT INTO wp_comments
	(comment_ID, comment_content, comment_author, comment_author_email, comment_author_url, comment_author_IP, comment_agent, comment_type)
VALUES
	(73, 'tquxjmjkvxdomkieuwdoxjmpgsubea', 'Commenter 73', 'user73@example.com', 'http://wzmnxycxbt', '198.51.100.74', 'python-requests/2.23.0', 'comment'),
	(74, 'lipxhsjgaljbpfngmkvcpbhmejnqjd', 'Commenter 74', 'user74@example.com', 'http://vlbfrriymi', '203.0.113.75', 'python-requests/2.23.0', 'comment'),
	(75, 'Karen cole paper LLC', 'Commenter 75', 'user75@example.com', '', '198.51.100.76', 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36', 'comment'),
	(76, 'IC', 'Commenter 76', 'user76@example.com', 'https://www.thevibes.com/articles/news/15622/2-fund-managers-picked-for-penjana-vc-scheme-linked-to-tengku-zafrul', '203.0.113.77', 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3450.0 Iron Safari/537.36 Puffin/7.5.3.392 Edge/12.0 Iridium/50.2 AppleWebKit/537.36 Chrome/62', 'comment'),
	(77, 'WE', 'Commenter 77', 'user77@example.com', 'https://digitalspeaks.com/community/profile/dexter01191977/', '198.51.100.78', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/2018.4 Safari/537.36 Chrome/66.0.3359.130', 'comment'),
	(78, 'NI', 'Commenter 78', 'user78@example.com', 'https://neuronsk.ru:443/bitrix/rk.php?goto=https://campsite.bio/entrepreneursprogramme', '203.0.113.79', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.106 Safari/537.36', 'comment'),
	(79, 'Hey Bernhard Kau, 
I want to ask you some questions about WordPress, would you mind telling me your email or any kinds of contact that I can reach out to you. 
Thanks in advance.', 'Commenter 79', 'user79@example.com', '', '198.51.100.80', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 'comment'),
	(80, 'Rotometrics', 'Commenter 80', 'user80@example.com', 'http://url.za.com/kw0om', '203.0.113.81', 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36', 'comment'),
	(81, 'Expressability', 'Commenter 81', 'user81@example.com', '', '198.51.100.82', 'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'comment'),
	(82, 'Informasi ini bagus', 'Commenter 82', 'user82@example.com', 'https://fasilkom.esaunggul.ac.id/', '203.0.113.83', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36', 'comment'),
	(83, '[&#8230;] Source: Hidden BIOS Setting for USB power supply on a Thinkpad | Kau-Boys [&#8230;]', 'Commenter 83', 'user83@example.com', 'https://www.wnxms.com/number-keypad-usb-of-2021', '198.51.100.84', 'The Incutio XML-RPC PHP Library -- WordPress/5.6.1', 'pingback'),
	(84, '[&#8230;] Источник [&#8230;]', 'Commenter 84', 'user84@example.com', 'https://laptopprocessors.ru/what-do-you-want-to-do-about-modified-configuration-file-php-ini/', '203.0.113.85', 'The Incutio XML-RPC PHP Library -- WordPress/6.3.1', 'pingback'),
	(85, '[&#8230;] Repair a broken Git Repository file system [&#8230;]', 'Commenter 85', 'user85@example.com', 'https://kau-boys.com/3677/misc/a-fifteen-year-old-teen-who-doesnt-know-what-to-wear', '198.51.100.86', 'The Incutio XML-RPC PHP Library -- WordPress/6.5.4', 'pingback'),
	(86, '[&#8230;] Create users in WordPress using the REST API [&#8230;]', 'Commenter 86', 'user86@example.com', 'https://kau-boys.com/3677/misc/a-fifteen-year-old-teen-who-doesnt-know-what-to-wear', '203.0.113.87', 'The Incutio XML-RPC PHP Library -- WordPress/6.5.4', 'pingback'),
	(87, '[&#8230;] Bonus Cashback: Mengalami kekalahan? Jangan kuatir, KUBET memberikan cashback yang siap menyelamatkan hari kau. [&#8230;]', 'Commenter 87', 'user87@example.com', 'https://buynbagit.com/master-togel-x-kubet-kombinasi-sempurna-untuk-pemain-slot-indonesia-siap-hasilkan-cuan-optimal-35/', '198.51.100.88', 'The Incutio XML-RPC PHP Library -- WordPress/5.8.10', 'pingback'),
	(88, '[&#8230;]  Read Full Article  [&#8230;]', 'Commenter 88', 'user88@example.com', 'https://www.wpnews.io/adding-a-custom-panel-to-query-monitor/', '203.0.113.89', 'The Incutio XML-RPC PHP Library -- WordPress/6.8.1', 'pingback'),
	(89, '[&#8230;] organizer, started an Advent Calendar to showcase recommended plugins. The Dec. 3 edition featured Block Editor: Reverse Columns on Mobile – a small block options plugin. He likes it for its ability to solve mobile layout issues with just 250 lines of code, managing [&#8230;]', 'Commenter 89', 'user89@example.com', 'https://gutenbergtimes.com/state-of-the-word-wordpress-6-9-gene-playground-year-review-weekend-edition-352/', '198.51.100.90', 'The Incutio XML-RPC PHP Library -- WordPress/6.9', 'pingback'),
	(90, '[&#8230;] organizer, started an Advent Calendar to showcase recommended plugins. The Dec. 3 edition featured Block Editor: Reverse Columns on Mobile – a small block options plugin. He likes it for its ability to solve mobile layout issues with just 250 lines of code, managing [&#8230;]', 'Commenter 90', 'user90@example.com', 'https://becon.digitaglobalgroup.com/2025/12/06/gutenberg-times-state-of-the-word-wordpress-6-9-gene-playground-year-review-weekend-edition-352/', '203.0.113.91', 'The Incutio XML-RPC PHP Library -- WordPress/6.9', 'pingback'),
	(91, '[&#8230;] organizer, started an Advent Calendar to showcase recommended plugins. The Dec. 3 edition featured Block Editor: Reverse Columns on Mobile – a small block options plugin. He likes it for its ability to solve mobile layout issues with just 250 lines of code, managing [&#8230;]', 'Commenter 91', 'user91@example.com', 'https://justgameworld.games/gutenberg-times-state-of-the-word-wordpress-6-9-gene-playground-year-review-weekend-edition-352/', '198.51.100.92', 'The Incutio XML-RPC PHP Library -- WordPress/6.9', 'pingback'),
	(92, '[&#8230;] organizer, started an Advent Calendar to showcase recommended plugins. The Dec. 3 edition featured Block Editor: Reverse Columns on Mobile – a small block options plugin. He likes it for its ability to solve mobile layout issues with just 250 lines of code, managing [&#8230;]', 'Commenter 92', 'user92@example.com', 'https://slamo.biochem.dal.ca/2025/12/06/gutenberg-times-state-of-the-word-wordpress-6-9-gene-playground-year-review-weekend-edition-352/', '203.0.113.93', 'The Incutio XML-RPC PHP Library -- WordPress/6.9', 'pingback'),
	(93, '<strong>...Click here for or more Information</strong>

[...]Nice blog here! Also your website lots up fast![...]', 'Commenter 93', 'user93@example.com', 'https://sites.google.com/view/investments777/home/', '198.51.100.94', '', 'trackback'),
	(94, '<strong>чувства тревоги</strong>

[...] What web host are you using? Can I get affiliate hyperlink in your host? I want site loaded up as quickly as yours lol[...]', 'Commenter 94', 'user94@example.com', 'http://1025h.com/wp/?wptouch_switch=mobile', '203.0.113.95', '', 'trackback'),
	(95, '<strong>тревоги чувства</strong>

[...]Wow, incredible blog format! How long have you been blogging for?[...]', 'Commenter 95', 'user95@example.com', 'https://techplanet.today/post/kak-izbavitsya-ot-trevogi-iz-za-bespokoistv-straxa-navyazcivyx-myslei', '198.51.100.96', '', 'trackback'),
	(96, '<strong>страха самостоятельно</strong>

[...]The whole look of your web site is fantastic, let well as the content material![...]', 'Commenter 96', 'user96@example.com', 'https://techplanet.today/post/kak-izbavitsya-ot-trevogi-iz-za-bespokoistv-straxa-navyazcivyx-myslei#1000', '203.0.113.97', '', 'trackback'),
	(97, '<strong>тревоги постоянного</strong>

[...] What host are you using? Can I am getting your associate link on your host? I want site loaded up as fast as yours lol[...]', 'Commenter 97', 'user97@example.com', 'https://techplanet.today/post/kak-izbavitsya-ot-trevogi-iz-za-bespokoistv-straxa-navyazcivyx-myslei#200', '198.51.100.98', '', 'trackback'),
	(98, '<strong>funziona reduslim</strong>

[...] What web host are you using? Can I get affiliate hyperlink in your host? I want site loaded up as quickly as yours lol[...]', 'Commenter 98', 'user98@example.com', 'https://techplanet.today/post/reduslim-per-dimagrante-la-verit-prezzo-in-farmacia-recensioni-vere-opinioni', '203.0.113.99', '', 'trackback'),
	(99, '<strong>reduslim dimagrante</strong>

[...] What web host are you the usage of? Can I get affiliate hyperlink in your host? I wish web site loaded up as quickly as yours lol[...]', 'Commenter 99', 'user99@example.com', 'http://1000love.net/lovelove/link.php?url=https://techplanet.today/post/reduslim-per-dimagrante-la-verit-prezzo-in-farmacia-recensioni-vere-opinioni', '198.51.100.100', '', 'trackback'),
	(100, '<strong>reduslim farmacia online</strong>

[...] What web host are you the usage of? Can I get affiliate hyperlink in your host? I wish web site loaded up as quickly as yours lol[...]', 'Commenter 100', 'user100@example.com', 'http://100not.ru/redirect.php?u=https://techplanet.today/post/reduslim-per-dimagrante-la-verit-prezzo-in-farmacia-recensioni-vere-opinioni', '203.0.113.101', '', 'trackback'),
	(101, '<strong>pastiglie reduslim</strong>

[...]The entire glance of your web site is wonderful, let well as the content![...]', 'Commenter 101', 'user101@example.com', 'http://168friend.com/externalpage.php?url=https://techplanet.today/post/reduslim-per-dimagrante-la-verit-prezzo-in-farmacia-recensioni-vere-opinioni', '198.51.100.102', '', 'trackback'),
	(102, '<strong>http://iranian-architect.ir/project-0060</strong>

[...]The overall look of your website is excellent, let neatly as the content material![...]', 'Commenter 102', 'user102@example.com', 'http://1c-hotel.com/bitrix/redirect.php?goto=https://techplanet.today/post/reduslim-per-dimagrante-la-verit-prezzo-in-farmacia-recensioni-vere-opinioni', '203.0.113.103', '', 'trackback');

-- regexp — 10 row(s) [comment ×10] — matched a spam regex pattern
INSERT INTO wp_comments
	(comment_ID, comment_content, comment_author, comment_author_email, comment_author_url, comment_author_IP, comment_agent, comment_type)
VALUES
	(103, 'Wie oft ich das mir vorstelle: Ein Kunde fragt bei der Anmeldung: Warum dauert das so lange? und ich sage: Ihr wisst, wir haben 15 Millionen Kommentare hier, und die sind alle mit display:none versteckt, weil sonst der Login-Button zu groß wird. 😉 Danke für diesen tiefgründigen Einblick in die WordPress-Performance-Magie!<a href="https://noimnothuman.org/" rel="nofollow ugc">アイム ノット ヒューマン</a>', 'Commenter 103', 'user103@example.com', 'https://noimnothuman.org/', '198.51.100.104', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(104, 'Hervorragender Artikel! Die Idee, die Kommentare auf der Checkout-Seite im Spam-Queue zu haben, ist ein klassisches Beispiel für Weniger ist mehr. Die Lösung mit dem Index war natürlich der Hammer – wer hätte gedacht, dass man mit einer einzigen SQL-Anweisung so viel Geschwindigkeit einspart? Die Moral der Geschichte: Manchmal muss man nicht alles löschen, um die Probleme zu lösen – nur diejenigen, die man wirklich nicht braucht (wie die Kommentare über die Lieferzeit der Banane). Und ja, ich habe auch schon bei kleineren Sites das eine oder andere Mal mit langsam laufenden Queries zu kämpfen gehabt, aber das ist ja gerade der Spaß bei WordPress. 😉<a href="https://ai-watermark-remover.com/" rel="nofollow ugc">ai watermark removal</a>', 'Commenter 104', 'user104@example.com', 'https://ai-watermark-remover.com/', '203.0.113.105', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(105, 'Hervorragend erläutert! Manchmal sind die perfidensten Performance-Bugs die kleinsten: zwei doofe Kommentare, die keiner braucht. Aber die Lösung mit dem Index – Beeindruckend, wie ein simples ALTER TABLE Wunder wirken kann! Bei mir hier ist das Problem eher, dass mein Kater bei jeder Page-Load-Animation über die Maus schaut. 😹 Danke für den Denkanstoß!<a href="https://zhuoruihk.com" rel="nofollow ugc">properties stainless steel</a>', 'Commenter 105', 'user105@example.com', 'https://zhuoruihk.com', '198.51.100.106', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(106, 'Hervorragender Artikel! Die Lösung, die die Kommentare zu order_note und user_membership_note einfach zu löschen, ist einfach brilliant und erinnert an das Lösen eines Flussschiffunfalls, indem man die Flussmitte einfach auskleidet. 😂 Die Tatsache, dass man für die anderen Probleme entweder einen Index hinzufügen oder ein Filtern benötigen würde, ist ja klar – aber das Löschen war definitiv der einfachste Weg. Komödiantisch!<a href="https://donghodemnguoc.org/" rel="nofollow ugc">đếm ngược giờ</a>', 'Commenter 106', 'user106@example.com', 'https://donghodemnguoc.org/', '203.0.113.107', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(107, 'Dieses Blogbeitrag ist eine wahre Comedie der Performance-Optimierung! Die Absurdität, dass man auf einer riesigen Shop-Installation mit über 15 Millionen Kommentare (wovon fast die Hälfte keine echte Komentare sind!) durch ein hidden Widget mit 2-User-IDs den Login um 2,5 Minuten verzögert, ist fast zu viel für das Gehirn. Die Lösung, die man sich vorstellt, ist fast noch schlimmer: Lösche die Kommentare oder füge einen Index hinzu – beides ist im Großen und Ganzen eine schiere Hölle. Gut, dass es nur zwei User waren, sonst wäre das Ganze ein echtes Katastrophenszenario gewesen. Aber hey, das ist doch nur WordPress, nicht wahr? 😂<a href="https://footballbros.run/" rel="nofollow ugc">football.bros</a>', 'Commenter 107', 'user107@example.com', 'https://footballbros.run/', '198.51.100.108', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(108, 'Das ist ja ein klassisches Beispiel für Performance durch Indexierung! 😂 Wer hätte gedacht, dass man mit über 15 Millionen Kommentaren (wobei einige ja keine echten Kommentare sind) in WordPress so ins Schwitzen kommen kann. Die Idee, die Kommentare einfach zu löschen (Solution 1), ist amüsant, aber leider meist keine dauerhafte Lösung. Solution 2 mit dem Filter ist super praktisch, besonders wenn man weiß, welche Schattenkommentare man weglassen kann. Solution 3, den Index hinzuzufügen, ist der wahre Hammer – aber man muss die Datenbank dafür schon mal etwas quälen lassen. Die Moral: Auch bei WordPress-Giganten muss man mal handwerklich zur Waffe greifen! 🛠️ Und ja, ein Tool wie Query Monitor ist wirklich Gold wert. Wer kennt das nicht? 😄<a href="https://growagarden-calculator.org/" rel="nofollow ugc">grow a garden calculator</a>', 'Commenter 108', 'user108@example.com', 'https://growagarden-calculator.org/', '203.0.113.109', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(109, 'Hervorragend erklärt! 😄 Dass man bei einer Million Bestellungen auf der Suche nach einer komischen Notiz für die Zahlungsseite 2,5 Minuten warten muss, ist ja wirklich eine kleine kleine Sache. Ich fand den Humor um die millionenkommentaren und die Lösung per Löschen (oder in den Papierkorb schieben) super. Und ja, ein Index wäre wohl auch eine nette Ergänzung gewesen, wenn man denn Zeit und Rechte hätte. Vielen Dank für die gelungene und lehrreiche Auseinandersetzung mit WordPress-Performance! 🚀<a href="https://ai-watermark-remover.com/" rel="nofollow ugc">ai removing watermarks</a>', 'Commenter 109', 'user109@example.com', 'https://ai-watermark-remover.com/', '198.51.100.110', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(110, 'Hervorragend erkläre die Komplexität! 😂 Und ja, die Lösung Kommentare löschen ist wohl die einfachste, wenn man sich die Zeit nehmen kann – besonders wenn die betroffenen Kommentare ja eh keine sind. Bei mir sind es meist die 15 Millionen Wichtigste Nachricht der Welt-Kommentare, dies verlangsamen, die ich dann lieber per WP-CLI in die Tonne tun muss. Und ein Index? Ach ja, dafür muss man ja schon einen eigenen Server mit Superlativen betreiben. Gut dass es solche Tipps gibt, sonst könnten wir alle nur noch mit dem Kopf gegen die Wand stossen – und das ist ja auch eine Art Kommentar! 😉<a href="https://taivideo.net/" rel="nofollow ugc">tải video YouTube</a>', 'Commenter 110', 'user110@example.com', 'https://taivideo.net/', '203.0.113.111', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0', 'comment'),
	(111, 'Imagine showing up first whenever someone searches for your product or service - that\'s what we make happen.

We launch campaigns in less than 24 hours, and you\'ll immediately start seeing targeted visitors coming to your site.
Can I show you how easy it is to get started?We help businesses get seen online fast - usually within 24 hours. You choose the keywords, and we drive the right visitors straight to your site.
Can I show you how it works?', 'Commenter 111', 'user111@example.com', 'https://www.google.com', '198.51.100.112', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0', 'comment'),
	(112, 'Great article!', 'Commenter 112', 'user112@example.com', 'https://tophatters.co', '203.0.113.113', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', 'comment');

-- title_is_name — 10 row(s) [trackback ×10] — linkback title equals the blog name
INSERT INTO wp_comments
	(comment_ID, comment_content, comment_author, comment_author_email, comment_author_url, comment_author_IP, comment_agent, comment_type)
VALUES
	(113, '<strong>movers nyc</strong>

movers nyc movers nyc movers nyc, movers nyc.', 'Commenter 113', 'user113@example.com', 'https://mypieceofcakemove.com', '198.51.100.114', 'python-requests/2.26.0', 'trackback'),
	(114, '<strong>IPTVresellerusa</strong>

blog topic', 'Commenter 114', 'user114@example.com', 'https://iptv-reseller.us/', '203.0.113.115', 'PHP/5.3.54', 'trackback'),
	(115, '<strong>implanty torun</strong>

blog topic', 'Commenter 115', 'user115@example.com', 'http://www.dentysta-inowroclaw.pl/jak-dobrze-nalezy-dbac-o-implanty-zebowe/', '198.51.100.116', 'PHP/5.3.82', 'trackback'),
	(116, '<strong>https://bit.ly/3RPFrou</strong>

Big spelling reform in the WWW: HTML 5 is now HTML5 - Kau-Boys', 'Commenter 116', 'user116@example.com', 'https://igame-24.com/', '203.0.113.117', 'PHP/5.2.64', 'trackback'),
	(117, '<strong>Jasa pembuatan pt tangerang</strong>

blog topic', 'Commenter 117', 'user117@example.com', 'https://www.instagram.com/legalistindonesia/', '198.51.100.118', 'PHP/5.3.35', 'trackback'),
	(118, '<strong>igame 24</strong>

Big spelling reform in the WWW: HTML 5 is now HTML5 - Kau-Boys', 'Commenter 118', 'user118@example.com', 'https://bit.ly/3Byyu4u', '203.0.113.119', 'PHP/5.3.12', 'trackback'),
	(119, '<strong>https://bit.ly/3UNBdjt</strong>

Big spelling reform in the WWW: HTML 5 is now HTML5 - Kau-Boys', 'Commenter 119', 'user119@example.com', 'https://bit.ly/3UNBdjt', '198.51.100.120', 'PHP/5.2.14', 'trackback'),
	(120, '<strong>https://tinyurl.com/8tpx5h8d</strong>

Big spelling reform in the WWW: HTML 5 is now HTML5 - Kau-Boys', 'Commenter 120', 'user120@example.com', 'https://tinyurl.com/8tpx5h8d', '203.0.113.121', 'PHP/5.3.13', 'trackback'),
	(121, '<strong>klimatyzacja</strong>

blog topic', 'Commenter 121', 'user121@example.com', 'https://www.google.com/maps/d/viewer?mid=z_PzWUH6fWCs.ksH41d7_pWfY', '198.51.100.122', 'PHP/5.3.84', 'trackback'),
	(122, '<strong>best physiotherapist near me prices</strong>

Big spelling reform in the WWW: HTML 5 is now HTML5 - Kau-Boys', 'Commenter 122', 'user122@example.com', 'https://www.blogtalkradio.com/z5wgtje880', '203.0.113.123', 'PHP/5.3.76', 'trackback');

-- Original antispam_bee_reason per comment (drives the driver's css decoy replay).
INSERT INTO wp_commentmeta (comment_id, meta_key, meta_value)
VALUES
	(25, 'antispam_bee_reason', 'css'),
	(26, 'antispam_bee_reason', 'css'),
	(27, 'antispam_bee_reason', 'css'),
	(28, 'antispam_bee_reason', 'css'),
	(29, 'antispam_bee_reason', 'css'),
	(30, 'antispam_bee_reason', 'css'),
	(31, 'antispam_bee_reason', 'css'),
	(32, 'antispam_bee_reason', 'css'),
	(33, 'antispam_bee_reason', 'css'),
	(34, 'antispam_bee_reason', 'css'),
	(35, 'antispam_bee_reason', 'empty'),
	(36, 'antispam_bee_reason', 'empty'),
	(37, 'antispam_bee_reason', 'empty'),
	(38, 'antispam_bee_reason', 'empty'),
	(39, 'antispam_bee_reason', 'empty'),
	(40, 'antispam_bee_reason', 'empty'),
	(41, 'antispam_bee_reason', 'empty'),
	(42, 'antispam_bee_reason', 'empty'),
	(43, 'antispam_bee_reason', 'empty'),
	(44, 'antispam_bee_reason', 'empty'),
	(45, 'antispam_bee_reason', 'localdb'),
	(46, 'antispam_bee_reason', 'localdb'),
	(47, 'antispam_bee_reason', 'localdb'),
	(48, 'antispam_bee_reason', 'localdb'),
	(49, 'antispam_bee_reason', 'localdb'),
	(50, 'antispam_bee_reason', 'localdb'),
	(51, 'antispam_bee_reason', 'localdb'),
	(52, 'antispam_bee_reason', 'localdb'),
	(53, 'antispam_bee_reason', 'localdb'),
	(54, 'antispam_bee_reason', 'localdb'),
	(55, 'antispam_bee_reason', 'localdb'),
	(56, 'antispam_bee_reason', 'localdb'),
	(57, 'antispam_bee_reason', 'localdb'),
	(58, 'antispam_bee_reason', 'localdb'),
	(59, 'antispam_bee_reason', 'localdb'),
	(60, 'antispam_bee_reason', 'localdb'),
	(61, 'antispam_bee_reason', 'localdb'),
	(62, 'antispam_bee_reason', 'localdb'),
	(63, 'antispam_bee_reason', 'localdb'),
	(64, 'antispam_bee_reason', 'localdb'),
	(65, 'antispam_bee_reason', 'localdb'),
	(66, 'antispam_bee_reason', 'localdb'),
	(67, 'antispam_bee_reason', 'localdb'),
	(68, 'antispam_bee_reason', 'localdb'),
	(69, 'antispam_bee_reason', 'localdb'),
	(70, 'antispam_bee_reason', 'localdb'),
	(71, 'antispam_bee_reason', 'localdb'),
	(72, 'antispam_bee_reason', 'localdb'),
	(73, 'antispam_bee_reason', 'manually'),
	(74, 'antispam_bee_reason', 'manually'),
	(75, 'antispam_bee_reason', 'manually'),
	(76, 'antispam_bee_reason', 'manually'),
	(77, 'antispam_bee_reason', 'manually'),
	(78, 'antispam_bee_reason', 'manually'),
	(79, 'antispam_bee_reason', 'manually'),
	(80, 'antispam_bee_reason', 'manually'),
	(81, 'antispam_bee_reason', 'manually'),
	(82, 'antispam_bee_reason', 'manually'),
	(83, 'antispam_bee_reason', 'manually'),
	(84, 'antispam_bee_reason', 'manually'),
	(85, 'antispam_bee_reason', 'manually'),
	(86, 'antispam_bee_reason', 'manually'),
	(87, 'antispam_bee_reason', 'manually'),
	(88, 'antispam_bee_reason', 'manually'),
	(89, 'antispam_bee_reason', 'manually'),
	(90, 'antispam_bee_reason', 'manually'),
	(91, 'antispam_bee_reason', 'manually'),
	(92, 'antispam_bee_reason', 'manually'),
	(93, 'antispam_bee_reason', 'manually'),
	(94, 'antispam_bee_reason', 'manually'),
	(95, 'antispam_bee_reason', 'manually'),
	(96, 'antispam_bee_reason', 'manually'),
	(97, 'antispam_bee_reason', 'manually'),
	(98, 'antispam_bee_reason', 'manually'),
	(99, 'antispam_bee_reason', 'manually'),
	(100, 'antispam_bee_reason', 'manually'),
	(101, 'antispam_bee_reason', 'manually'),
	(102, 'antispam_bee_reason', 'manually'),
	(103, 'antispam_bee_reason', 'regexp'),
	(104, 'antispam_bee_reason', 'regexp'),
	(105, 'antispam_bee_reason', 'regexp'),
	(106, 'antispam_bee_reason', 'regexp'),
	(107, 'antispam_bee_reason', 'regexp'),
	(108, 'antispam_bee_reason', 'regexp'),
	(109, 'antispam_bee_reason', 'regexp'),
	(110, 'antispam_bee_reason', 'regexp'),
	(111, 'antispam_bee_reason', 'regexp'),
	(112, 'antispam_bee_reason', 'regexp'),
	(113, 'antispam_bee_reason', 'title_is_name'),
	(114, 'antispam_bee_reason', 'title_is_name'),
	(115, 'antispam_bee_reason', 'title_is_name'),
	(116, 'antispam_bee_reason', 'title_is_name'),
	(117, 'antispam_bee_reason', 'title_is_name'),
	(118, 'antispam_bee_reason', 'title_is_name'),
	(119, 'antispam_bee_reason', 'title_is_name'),
	(120, 'antispam_bee_reason', 'title_is_name'),
	(121, 'antispam_bee_reason', 'title_is_name'),
	(122, 'antispam_bee_reason', 'title_is_name');
